#define SUM_THRESHOLD 5000
#define ANGLE_ERROR_THRESHOLD 10
#define UPDATE_INTERVAL 5
#define MOTOR_COUNT 3

#define VIA_INTERVAL 100
#define VIA_COUNT 10

enum STATE {ST_IDLE, ST_HOLDING, ST_MOVING};
